#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo -e "===\n>> Pre-push Hook: Checking linters ..."

yarn format:check && yarn eslint:check

echo -e "===\n>> Pre-push Hook: Checking branch name ..."

BRANCH=$(git rev-parse --abbrev-ref HEAD)
PROTECTED_BRANCHES="^(master|main|staging|development|production)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]; then
  echo -e "\n🚫 Cannot push to protected remote $BRANCH branch, please checkout to a feature branch and create a Pull Request." && exit 1
fi

echo -e ">> Finish checking branch name \n==="

exit 0
